matrix:
  include:
    - os: linux
      language: c
      compiler: gcc
      script:
        - cd example
        - make && ./NComToCsv 171019_031603.ncom 171019_031603.csv
        - cd ..
        - python test.py

    - os: osx
      language: c
      compiler: gcc
      script:
        - cd example
        - make && ./NComToCsv 171019_031603.ncom 171019_031603.csv
        - cd ..
        - python test.py

    - os: windows
      language: c
      compiler: gcc
      cache:
        directories:
          - $HOME/AppData/Local/Temp/chocolatey
      before_install:
        - choco install python --version 3.8.6
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
      script:
        - cd example
        - mingw32-make.exe && ./NComToCsv.exe 171019_031603.ncom 171019_031603.csv
        - cd ..
        - python test.py
